### ISSUE TITLE
About The Paper

### ISSUE THREAD

**Issue by lunaWU628** [abhishek1411/event-rgb-fusion#2]
Hello, this is a great job. Can I have a look at the paper? I can't download it in https://hal.archives-ouvertes.fr/hal-03591717/. I hope you can help me, thank you!

**Comment by abhishek1411** [comment]
Hello, the paper should now be available online here:
[link]( https://hal.archives-ouvertes.fr/hal-03591717/document)

**Comment by lunaWU628** [comment]
Thank you so much. I hope everything goes well with you!
