### ISSUE TITLE
About the code

### ISSUE THREAD

**Issue by lunaWU628** [abhishek1411/event-rgb-fusion#4]
Hello,  
           Wonderful job! There is one question about the code:
           
![image](https://user-images.githubusercontent.com/90367095/176082114-cc96d362-78a4-4c5a-9cf0-2086cf0058f6.png)

These .txt files are written in binary. What is the content here, is it a picture?  And I wonder if the contents be visualized?

Any advice will help me. Thanks!

**Comment by abhishek1411** [comment]
Hello,
The annotations and detections are all the output of the network without setting the confidence threshold. This was done, so as to save time during evaluation. Once all the detections and their annotations are saved, it allowed us to evaluate various metrics (COCO mAP, mAP50, mAP 75 etc) without having to run the network each time over entire datasets. A sample of how these files are used can be seen in test.py or test_rgb.py.

**Comment by abhishek1411** [comment]
For visualization purposes, have a look at the file visualize.py

**Comment by lunaWU628** [comment]
Thanks！

I want to **confirm** that in order to visualize the results after  fusion,  which file should I run?  **'visualize.py**''or '**visualize_events.py**'?

**Comment by abhishek1411** [comment]
Visualize_events.py is for the events-only model. I have added the code to visualize the results from the sensor fusion model in the repository (visualize_fusion.py)

**Comment by lunaWU628** [comment]
I get it, and thank you for your prompt reply.  Hope everything goes well for you！
