### ISSUE TITLE
Homographic transformation

### ISSUE THREAD

**Issue by Zizzzzzzz** [abhishek1411/event-rgb-fusion#5]
Hello, it is a wonderful job! I have a question about the code. Do we need to implement the alignment between event data and RGB data by ourselves?

**Comment by abhishek1411** [comment]
You can find the code for alignemnet of RGB and event frame here:
[https://github.com/RunqiuBao/fov_alignment/blob/main/fov_align.ipynb](https://github.com/RunqiuBao/fov_alignment/blob/main/fov_align.ipynb)

**Comment by Zizzzzzzz** [comment]
Thanks!
